const portfolioData =  {
    "imagebaseurl": "http://localhost:3000/",
    "name": "Harshada Samant",
    "role": "Frontend Developer",
    "roleDescription": "based at Mumbai location and working on frontend techniques like HTML5, css3 and scss, bootstrap4 and Frontend frameworks like react, angular, angularJs",
    "aboutDescription": "I am self-motivated and passionate programmer, always looking for an opportunity to learn and grow. I love to interact with people and connect with them. I believe if we don't know something then it is ok but if we don't want to know something then there is a huge problem. ",
    "address": "Malad, Mumbai-400064, Maharashtra, India",
    "mobNumber": "9699975656",
    "mobHref": "tel:9699975656",
    "mailId": "harshadasamant03@gmail.com",
    "mailHref": "mailto:someone@example.com",
    "collegeName": "Garware College of Commerce",
    "universityName": "Savitribai Phule Pune University",
    "courseName": "Bachelor of Computer Application",
    "collegeDuration": "2015-2018",
    "collegeExperience": "college life",
    "jrCollegeName": "Sathaye College of Arts, Commerce, Science",
    "jrUniversityName": "University of Mumbai",
    "stream": "Science",
    "jrCollegeDuration": "2013-2015",
    "jrCollegeExperience": "jr college life",
    "schoolName": "Rani Laxmibai Girls Military School",
    "schoolBoard": "Maharashtra State Board of Secondary and Higher Secondary Education, Pune",
    "schoolDuration": "2008-2013",
    "schoolExperience": "school life",
    "work1": "LexStart - Legal & Compliance",
    "work1Duration": "",
    "work1Role": "Frontend Developer Intern",
    "work1Description": "Working with designers and backend team for UI development of company website and other internal tasks. Working on Html5, css3, sass, sass watch, bootstrap 4, javascript, jQuery, angularJs, git, Nginx server.",
    "work2": "NeoSOFT Technologies (A CMMi Level 5 Organization)",
    "work2Duration": "June 2019 - Present",
    "work2Role": "Frontend Developer",
    "work2Description": "Working closely with UI/UX designer and developing a user interface with HTML5, css3, sass, bootstrap 4, JavaScript, JSX, jQuery, Angular 8 framework, reusable code development and theme building using StencilJs and working with version control tools like git. Handling client projects with an agile methodology and be a part of the sprint meetings",
    "thankYouNote": "Thank you for vising my portfolio. You can connect with me using contact details as well as social media profile. Have a look at the github link to know more about my work."
}

export default portfolioData;